"ROBOT_HARDWARE_VERSION" : "ESTRELA"
"TOWER_TOP_MAX" : 8.0
"USE_VNA_SENSOR" : True
"PORTRAIT_CROP_PARALLEL_LIMIT": 3
"PORTRAIT_IMAGE_FORMAT": "avif"
"PORTRAIT_IMAGE_QUALITY": 40
"PORTRAIT_LOCATION_HEIGHT_PADDING_METRES": 0.25
"PORTRAIT_LOCATION_WIDTH_PADDING_METRES": 0.25
"ENABLE_NEW_WORKER_API": true
"USE_NEW_WORKER_API_FOR_IMAGES": true
"USE_UNIFIED_MISSION_EXECUTOR": true
"USE_NEW_BASE_LIDAR_FILTER" : true
