"""Configuration settings for Robosense devices."""

SENSOR_TYPES = {
    "helios": {
        "base_config": {
            "tabs-two": "on",
            "device_ip_addr": "",
            "device_ip_mask": "255.255.255.0",
            "device_ip_gateway": "172.16.0.254",
            "des_ip_addr": "172.16.0.1",
            "lidar_msop_port": "",
            "lidar_difop_port": "",
            "RetModeSel": "First",
            "lidar_fov_start": "0",
            "lidar_fov_end": "360",
            "phase_lock": "0",
            "RotationSpeed": "1200",
            "TimeSyncSrc": "PTP-E2E-L4",
            "ptp_domain_number": "0",
            "OperateMode": "High Performance",
            "reflectivityModeSel": "Off",
            "rainMistModeSel": "Off",
            "save_param": "Save",
            "mode1": "Mode1(+25%)",
        },
        "individual_config": {
            "Front Cover": {
                "device_ip_addr": "172.16.0.23",
                "lidar_msop_port": "6704",
                "lidar_difop_port": "7793",
            },
            "Rear Cover": {
                "device_ip_addr": "172.16.0.20",
                "lidar_msop_port": "6701",
                "lidar_difop_port": "7790",
            },
            "Section 2": {
                "device_ip_addr": "172.16.0.27",
                "lidar_msop_port": "6705",
                "lidar_difop_port": "7794",
            },
            "Section 3": {
                "device_ip_addr": "172.16.0.21",
                "lidar_msop_port": "6702",
                "lidar_difop_port": "7791",
            },
            "Section 4": {
                "device_ip_addr": "172.16.0.28",
                "lidar_msop_port": "6706",
                "lidar_difop_port": "7795",
            },
            "Section 5": {
                "device_ip_addr": "172.16.0.22",
                "lidar_msop_port": "6703",
                "lidar_difop_port": "7792",
            },
        },
        "robot_default_config": ["Front Cover", "Rear Cover", "Section 3", "Section 5"],
        "boundary": "----WebKitFormBoundaryrELA4R3ej9eUZ5uA",
        "target_url": "/cgi-bin/param_setting.cgi",
    },
    "bpearl": {
        "base_config": {
            "tabs-two": "on",
            "device_ip_addr": "",
            "device_ip_mask": "255.255.255.0",
            "device_ip_gateway": "172.16.0.254",
            "des_ip_addr": "172.16.0.1",
            "lidar_msop_port": "",
            "lidar_difop_port": "",
            "ret_mode_sel": "Strong",
            "lidar_fov_start": "0",
            "lidar_fov_end": "360",
            "time_sync_src": "PTP-E2E-L4",
            "ptp_domain_number": "0",
            "nonlinear_mapping": "OFF",
            "operate_mode": "Balance",
            "phase_lock": "0",
            "rotation_speed": "600",
            "gps_baud_rate": "9600",
            "save_param": "Save",
        },
        "individual_config": {
            "Front B-Pearl": {
                "device_ip_addr": "172.16.0.11",
                "lidar_msop_port": "6699",
                "lidar_difop_port": "7788",
            },
            "Rear B-Pearl": {
                "device_ip_addr": "172.16.0.12",
                "lidar_msop_port": "6700",
                "lidar_difop_port": "7789",
            },
        },
        "robot_default_config": ["Front B-Pearl", "Rear B-Pearl"],
        "boundary": "----WebKitFormBoundaryy6YoPjFsHIPk7DEw",
        "target_url": "/cgi-bin/param_setting.cgi",
    },
}
